# -*- coding: utf-8 -*-
"""
/***************************************************************************
 도면자동화플러그인
                                 A QGIS plugin
 이 플러그인은 도면 자동화 처리를 수행합니다
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-23
        copyright            : (C) 2025 by Wonsukhuh
        email                : wonsukhuh10@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


def classFactory(iface):
    """플러그인 클래스를 로드합니다"""
    from .domun_automation_plugin import DomunAutomationPlugin
    return DomunAutomationPlugin(iface)