# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DomunAutomationDialog
                                 A QGIS plugin
 이 플러그인은 도면 자동화 처리를 수행합니다
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-23
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Wonsukhuh
        email                : wonsukhuh10@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'domun_automation_dialog_base.ui'))


class DomunAutomationDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(DomunAutomationDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
    def append_status(self, message):
        """상태 메시지를 텍스트 에디터에 추가"""
        self.statusTextEdit.append(message)
        
    def clear_status(self):
        """상태 텍스트 초기화"""
        self.statusTextEdit.clear()